# Docker Compose 文件版本设置为 3.8，以利用更多高级特性和更好的兼容性。
version: '3.8' 

services:
  web:
    # 使用基于 Alpine Linux 的 Qinglong 镜像版本 2.17.4。
    image: whyour/qinglong:2.17.4

    # 注释掉的行提供了使用基于 Debian 的 slim 版本的选项。
    # image: whyour/qinglong:debian-slim 

    # 定义持久化存储卷映射，将本地目录 ./data 与容器内的 /ql/data 路径绑定。
    volumes:
      - ./data:/ql/data  

    # 映射端口，允许外部通过主机的 5700 端口访问容器内部服务。
    ports:
      - "5700:5700"  

    # 设置环境变量，定义 Qinglong 的部署基础路径，默认为根路径。
    environment:
      QlBaseUrl: '/'  

    # 设置容器重启策略为 `unless-stopped`，即除非手动停止容器，否则容器将在遇到任何退出状态后自动重启。
    restart: unless-stopped  